### ISSUE TITLE
Peek differences

### ISSUE THREAD

**Issue by MulverineX** [VenPlugs/PersistFavourites#1]
![image](https://user-images.githubusercontent.com/12068027/119541797-0ee53a80-bd4c-11eb-920d-54ad3881950b.png)

This should let you peek at the differences, maybe a button that doesn't dismiss that prints both objects to console so you can look manually or something.

Also perhaps this could be avoided more often by backing up again in the `unload` function.

**Comment by Vendicated** [comment]
the reason this happens so often is because every time you use an emote discord updates your emote store. but currently I made it so that the plugin only backs up every 10 emoji track as I figured it'd be pretty laggy to stringify a massive json every time you use an emote. I need to find a better solution for this but yes the diff sounds like a nice idea

**Comment by slow** [comment]
This won't be an issue anymore due to #6
